version: "3.9"

services:
  vhtask-app:
    container_name: vhtask-app
    build: .
    environment:
      DATABASE_URL: "host=vhtask_db user=postgres password=postgres dbname=vhtask sslmode=disable"
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - vhtask_db

  vhtask_db:
    container_name: vhtask_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
